In [ ]:
%pip install -r ./../stellar_classification/requirements.txt

Requirement already satisfied: numpy in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 2)) (2.4.4)
Requirement already satisfied: pandas in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 3)) (3.0.2)
Requirement already satisfied: matplotlib in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 4)) (3.10.9)
Requirement already satisfied: seaborn in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: scikit-learn in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 6)) (1.8.0)
Requirement already satisfied: imbalanced-learn in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 7)) (0.14.1)
Requirement already satisfied: imblearn in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 8)) (0.0)
Requirement already satisfied: torch in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 9)) (2.11.0)
Requirement already satisfied: catboost in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 10)) (1.2.10)
Requirement already satisfied: lightgbm in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 11)) (4.6.0)
Requirement already satisfied: shap in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 12)) (0.51.0)
Requirement already satisfied: pyyaml in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 13)) (6.0.3)
Requirement already satisfied: tqdm in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from -r ./../stellar_classification/requirements.txt (line 14)) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from pandas->-r ./../stellar_classification/requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from matplotlib->-r ./../stellar_classification/requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from scikit-learn->-r ./../stellar_classification/requirements.txt (line 6)) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from scikit-learn->-r ./../stellar_classification/requirements.txt (line 6)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from scikit-learn->-r ./../stellar_classification/requirements.txt (line 6)) (3.6.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from imbalanced-learn->-r ./../stellar_classification/requirements.txt (line 7)) (0.1.5)
Requirement already satisfied: filelock in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (4.15.0)
Requirement already satisfied: setuptools<82 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (3.6.1)
Requirement already satisfied: jinja2 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (2026.3.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from torch->-r ./../stellar_classification/requirements.txt (line 9)) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch->-r ./../stellar_classification/requirements.txt (line 9)) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from cuda-bindings<14,>=13.0.3->torch->-r ./../stellar_classification/requirements.txt (line 9)) (1.5.4)
Requirement already satisfied: graphviz in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from catboost->-r ./../stellar_classification/requirements.txt (line 10)) (0.21)
Requirement already satisfied: plotly in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from catboost->-r ./../stellar_classification/requirements.txt (line 10)) (6.7.0)
Requirement already satisfied: six in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from catboost->-r ./../stellar_classification/requirements.txt (line 10)) (1.17.0)
Requirement already satisfied: slicer==0.0.8 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from shap->-r ./../stellar_classification/requirements.txt (line 12)) (0.0.8)
Requirement already satisfied: numba in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from shap->-r ./../stellar_classification/requirements.txt (line 12)) (0.65.1)
Requirement already satisfied: llvmlite in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from shap->-r ./../stellar_classification/requirements.txt (line 12)) (0.47.0)
Requirement already satisfied: cloudpickle in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from shap->-r ./../stellar_classification/requirements.txt (line 12)) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from sympy>=1.13.3->torch->-r ./../stellar_classification/requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from jinja2->torch->-r ./../stellar_classification/requirements.txt (line 9)) (3.0.3)
Requirement already satisfied: narwhals>=1.15.1 in /home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages (from plotly->catboost->-r ./../stellar_classification/requirements.txt (line 10)) (2.20.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import sys
import os
import gc
import pandas as pd
import matplotlib.pyplot as plt
import numpy

# Add the package root to sys.path so we can import stellar_classification
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', 'stellar_classification')))

import stellar_classification as sc

# Enable garbage collection
gc.enable()
gc.collect()

/home/ettore/anaconda3/envs/comp_astro/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

20

In [3]:
# Load dataset
data_path = './star_classification.csv'
star = pd.read_csv(data_path)

print("First few rows:")
display(star.head())

print("\nData Info:")
star.info()

print("\nNull Values:")
print(star.isnull().sum())

print("\nClass Distribution:")
print(star["class"].value_counts(normalize=True) * 100)

# -------- Color indexes ----------
star["u_g"] = star["u"] - star["g"]
star["g_r"] = star["g"] - star["r"]
star["r_i"] = star["r"] - star["i"]
star["i_z"] = star["i"] - star["z"]

display(star.head())

First few rows:

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
0,1.237661e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,2,79,6.543777e+18,GALAXY,0.634794,5812,56354,171
1,1.237665e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,5,119,1.176014e+19,GALAXY,0.779136,10445,58158,427
2,1.237661e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,2,120,5.152200e+18,GALAXY,0.644195,4576,55592,299
3,1.237663e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,3,214,1.030107e+19,GALAXY,0.932346,9149,58039,775
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,3,137,6.891865e+18,GALAXY,0.116123,6121,56187,842

Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   obj_ID       100000 non-null  float64
 1   alpha        100000 non-null  float64
 2   delta        100000 non-null  float64
 3   u            100000 non-null  float64
 4   g            100000 non-null  float64
 5   r            100000 non-null  float64
 6   i            100000 non-null  float64
 7   z            100000 non-null  float64
 8   run_ID       100000 non-null  int64
 9   rerun_ID     100000 non-null  int64
 10  cam_col      100000 non-null  int64
 11  field_ID     100000 non-null  int64
 12  spec_obj_ID  100000 non-null  float64
 13  class        100000 non-null  str
 14  redshift     100000 non-null  float64
 15  plate        100000 non-null  int64
 16  MJD          100000 non-null  int64
 17  fiber_ID     100000 non-null  int64
dtypes: float64(10), int64(7), str(1)
memory usage: 13.7 MB

Null Values:
obj_ID         0
alpha          0
delta          0
u              0
g              0
r              0
i              0
z              0
run_ID         0
rerun_ID       0
cam_col        0
field_ID       0
spec_obj_ID    0
class          0
redshift       0
plate          0
MJD            0
fiber_ID       0
dtype: int64

Class Distribution:
class
GALAXY    59.445
STAR      21.594
QSO       18.961
Name: proportion, dtype: float64

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,...,spec_obj_ID,class,redshift,plate,MJD,fiber_ID,u_g,g_r,r_i,i_z
0,1.237661e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,...,6.543777e+18,GALAXY,0.634794,5812,56354,171,1.60352,1.88029,1.22928,0.37202
1,1.237665e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,...,1.176014e+19,GALAXY,0.779136,10445,58158,427,1.94571,0.24744,1.41632,-0.44615
2,1.237661e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,...,5.152200e+18,GALAXY,0.644195,4576,55592,299,2.59918,2.05413,1.26119,0.40030
3,1.237663e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,...,1.030107e+19,GALAXY,0.932346,9149,58039,775,-1.63974,2.16494,1.10708,1.25444
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,...,6.891865e+18,GALAXY,0.116123,6121,56187,842,1.85690,1.08281,0.52036,0.43250

In [4]:
# Preprocessing: Apply outlier removal, splits, standardization, and SMOTE
X_train, X_val, X_test, y_train, y_val, y_test, label_encoder, scaler, feature_names = sc.prepare_splits(
    star, 
    target_col='class', 
    test_size=0.2, 
    val_ratio=0.25, 
    random_state=42, 
    apply_outlier_removal=True
)

print(f"X_train shape: {X_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"X_test shape: {X_test.shape}")

         obj_ID       alpha      delta         u        g         r         i  \
0  1.237661e+18  135.689107  32.494632  23.87882  22.2753  20.39501  19.16573

          z  run_ID  rerun_ID  ...   spec_obj_ID  class  redshift  plate  \
0  18.79371    3606       301  ...  6.543777e+18      0  0.634794   5812

     MJD  fiber_ID      u_g      g_r      r_i      i_z
0  56354       171  1.60352  1.88029  1.22928  0.37202

[1 rows x 22 columns]
        alpha      delta         u        g         r         i         z  \
0  135.689107  32.494632  23.87882  22.2753  20.39501  19.16573  18.79371

   class  plate    MJD      u_g      g_r      r_i      i_z
0      0   5812  56354  1.60352  1.88029  1.22928  0.37202
Outliers removed: 8,715 rows  (91,285 remain)
X_train shape: (97032, 13)
X_val shape: (18257, 13)
X_test shape: (18257, 13)

In [5]:
train_loader, val_loader, test_loader = sc.to_dataloaders(
    X_train, y_train,
    X_val, y_val,
    X_test, y_test,
    batch_size=64
)

print("DataLoaders created.")

DataLoaders created.

In [6]:
# ============================================================
# Neural Network setup
# ============================================================

input_size = X_train.shape[1]
num_classes = len(label_encoder.classes_)

print("Input size:", input_size)
print("Number of classes:", num_classes)

Input size: 13
Number of classes: 3

In [8]:
# ============================================================
# Import experiment runner
# ============================================================

from stellar_classification.experiments.nn_runner import run_experiments

In [9]:
# ============================================================
# Run Neural Network Experiments
# ============================================================

results_df = run_experiments(
    train_loader=train_loader,
    val_loader=val_loader,
    test_loader=test_loader,

    input_size=input_size,
    num_classes=num_classes,

    model_types=[
        "SimpleNN",
        "MediumNN",
        "ComplexNN",
    ],

    learning_rates=[
        0.01,
        0.001,
        0.0001,
    ],

    epochs=10,
)

 Training SimpleNN | lr=0.01
Epoch 1/10 | loss=0.4360 | val_acc=86.84%
Epoch 2/10 | loss=0.3866 | val_acc=85.00%
Epoch 3/10 | loss=0.3746 | val_acc=87.68%
Epoch 4/10 | loss=0.3659 | val_acc=87.46%
Epoch 5/10 | loss=0.3580 | val_acc=87.25%
Epoch 6/10 | loss=0.3554 | val_acc=86.39%
Epoch 7/10 | loss=0.3516 | val_acc=88.45%
Epoch 8/10 | loss=0.3504 | val_acc=86.62%
Epoch 9/10 | loss=0.3452 | val_acc=87.38%
Epoch 10/10 | loss=0.3469 | val_acc=86.39%
✔ Done: SimpleNN | lr=0.01 | F1=0.8345

 Training SimpleNN | lr=0.001
Epoch 1/10 | loss=0.4908 | val_acc=84.65%
Epoch 2/10 | loss=0.4168 | val_acc=86.38%
Epoch 3/10 | loss=0.3974 | val_acc=86.32%
Epoch 4/10 | loss=0.3845 | val_acc=87.31%
Epoch 5/10 | loss=0.3745 | val_acc=86.30%
Epoch 6/10 | loss=0.3661 | val_acc=87.27%
Epoch 7/10 | loss=0.3600 | val_acc=87.17%
Epoch 8/10 | loss=0.3538 | val_acc=85.91%
Epoch 9/10 | loss=0.3494 | val_acc=88.38%
Epoch 10/10 | loss=0.3452 | val_acc=87.55%
✔ Done: SimpleNN | lr=0.001 | F1=0.8456

 Training SimpleNN | lr=0.0001
Epoch 1/10 | loss=0.7055 | val_acc=79.37%
Epoch 2/10 | loss=0.5443 | val_acc=83.07%
Epoch 3/10 | loss=0.4904 | val_acc=84.33%
Epoch 4/10 | loss=0.4661 | val_acc=84.50%
Epoch 5/10 | loss=0.4542 | val_acc=84.84%
Epoch 6/10 | loss=0.4466 | val_acc=84.63%
Epoch 7/10 | loss=0.4411 | val_acc=85.04%
Epoch 8/10 | loss=0.4362 | val_acc=85.03%
Epoch 9/10 | loss=0.4322 | val_acc=85.24%
Epoch 10/10 | loss=0.4285 | val_acc=85.21%
✔ Done: SimpleNN | lr=0.0001 | F1=0.8192

 Training MediumNN | lr=0.01
Epoch 1/10 | loss=0.4023 | val_acc=85.21%
Epoch 2/10 | loss=0.3512 | val_acc=88.08%
Epoch 3/10 | loss=0.3362 | val_acc=87.29%
Epoch 4/10 | loss=0.3264 | val_acc=88.03%
Epoch 5/10 | loss=0.3228 | val_acc=87.92%
Epoch 6/10 | loss=0.3190 | val_acc=89.07%
Epoch 7/10 | loss=0.3157 | val_acc=86.99%
Epoch 8/10 | loss=0.3121 | val_acc=89.54%
Epoch 9/10 | loss=0.3095 | val_acc=89.25%
Epoch 10/10 | loss=0.3072 | val_acc=88.04%
✔ Done: MediumNN | lr=0.01 | F1=0.8537

 Training MediumNN | lr=0.001
Epoch 1/10 | loss=0.4304 | val_acc=87.28%
Epoch 2/10 | loss=0.3601 | val_acc=88.19%
Epoch 3/10 | loss=0.3411 | val_acc=87.91%
Epoch 4/10 | loss=0.3294 | val_acc=87.80%
Epoch 5/10 | loss=0.3220 | val_acc=88.31%
Epoch 6/10 | loss=0.3156 | val_acc=88.97%
Epoch 7/10 | loss=0.3089 | val_acc=88.23%
Epoch 8/10 | loss=0.3053 | val_acc=89.20%
Epoch 9/10 | loss=0.3008 | val_acc=88.45%
Epoch 10/10 | loss=0.2970 | val_acc=88.88%
✔ Done: MediumNN | lr=0.001 | F1=0.8609

 Training MediumNN | lr=0.0001
Epoch 1/10 | loss=0.6236 | val_acc=83.89%
Epoch 2/10 | loss=0.4510 | val_acc=85.07%
Epoch 3/10 | loss=0.4155 | val_acc=86.03%
Epoch 4/10 | loss=0.3997 | val_acc=86.35%
Epoch 5/10 | loss=0.3894 | val_acc=86.25%
Epoch 6/10 | loss=0.3809 | val_acc=86.88%
Epoch 7/10 | loss=0.3742 | val_acc=87.40%
Epoch 8/10 | loss=0.3685 | val_acc=87.00%
Epoch 9/10 | loss=0.3633 | val_acc=87.00%
Epoch 10/10 | loss=0.3591 | val_acc=87.77%
✔ Done: MediumNN | lr=0.0001 | F1=0.8470

 Training ComplexNN | lr=0.01
Epoch 1/10 | loss=0.4202 | val_acc=85.88%
Epoch 2/10 | loss=0.3673 | val_acc=87.28%
Epoch 3/10 | loss=0.3464 | val_acc=87.46%
Epoch 4/10 | loss=0.3400 | val_acc=88.66%
Epoch 5/10 | loss=0.3343 | val_acc=88.25%
Epoch 6/10 | loss=0.3276 | val_acc=86.85%
Epoch 7/10 | loss=0.3214 | val_acc=88.04%
Epoch 8/10 | loss=0.3207 | val_acc=89.20%
Epoch 9/10 | loss=0.3152 | val_acc=88.05%
Epoch 10/10 | loss=0.3172 | val_acc=86.60%
✔ Done: ComplexNN | lr=0.01 | F1=0.8380

 Training ComplexNN | lr=0.001
Epoch 1/10 | loss=0.3895 | val_acc=87.55%
Epoch 2/10 | loss=0.3325 | val_acc=86.54%
Epoch 3/10 | loss=0.3128 | val_acc=88.51%
Epoch 4/10 | loss=0.2998 | val_acc=88.68%
Epoch 5/10 | loss=0.2889 | val_acc=88.47%
Epoch 6/10 | loss=0.2795 | val_acc=89.78%
Epoch 7/10 | loss=0.2694 | val_acc=89.77%
Epoch 8/10 | loss=0.2597 | val_acc=89.15%
Epoch 9/10 | loss=0.2518 | val_acc=89.58%
Epoch 10/10 | loss=0.2423 | val_acc=89.40%
✔ Done: ComplexNN | lr=0.001 | F1=0.8670

 Training ComplexNN | lr=0.0001
Epoch 1/10 | loss=0.4650 | val_acc=87.16%
Epoch 2/10 | loss=0.3661 | val_acc=87.18%
Epoch 3/10 | loss=0.3467 | val_acc=88.08%
Epoch 4/10 | loss=0.3340 | val_acc=87.96%
Epoch 5/10 | loss=0.3238 | val_acc=88.31%
Epoch 6/10 | loss=0.3163 | val_acc=88.75%
Epoch 7/10 | loss=0.3106 | val_acc=88.28%
Epoch 8/10 | loss=0.3046 | val_acc=88.56%
Epoch 9/10 | loss=0.2999 | val_acc=88.60%
Epoch 10/10 | loss=0.2957 | val_acc=89.08%
✔ Done: ComplexNN | lr=0.0001 | F1=0.8631

 BEST CONFIGURATION:
model            ComplexNN
learning_rate        0.001
val_accuracy     89.401326
val_f1            0.867026
test_accuracy    89.812127
test_f1            0.87114
Name: 7, dtype: object

 TOP 5:
       model  learning_rate  val_accuracy    val_f1  test_accuracy   test_f1
7  ComplexNN         0.0010     89.401326  0.867026      89.812127  0.871140
8  ComplexNN         0.0001     89.078162  0.863067      89.527305  0.867685
4   MediumNN         0.0010     88.875500  0.860938      89.204141  0.864739
3   MediumNN         0.0100     88.037465  0.853666      88.245604  0.855475
5   MediumNN         0.0001     87.774552  0.847040      88.004601  0.849395

In [10]:
# ============================================================
# Results
# ============================================================

display(results_df)

       model  learning_rate  val_accuracy    val_f1  test_accuracy   test_f1
7  ComplexNN         0.0010     89.401326  0.867026      89.812127  0.871140
8  ComplexNN         0.0001     89.078162  0.863067      89.527305  0.867685
4   MediumNN         0.0010     88.875500  0.860938      89.204141  0.864739
3   MediumNN         0.0100     88.037465  0.853666      88.245604  0.855475
5   MediumNN         0.0001     87.774552  0.847040      88.004601  0.849395
1   SimpleNN         0.0010     87.549981  0.845550      88.103193  0.851222
6  ComplexNN         0.0100     86.596922  0.838015      86.941995  0.841197
0   SimpleNN         0.0100     86.388782  0.834465      86.772197  0.838724
2   SimpleNN         0.0001     85.205675  0.819166      85.572657  0.823002